List<Map<String, dynamic>> exploreProducts = [
  {
    "room": "images/explore/livingroom1.png",
    "isLiked": false,
    "details": [
      {
        "image": "images/explore_details/livingroom1_1.png",
        "name": "Artificial Tree",
        "stock": "23",
        "rating": "4.8",
        "price1": 125,
        "size": "80cm,40cm,40cm",
        "type": "plants",
        "weight": "4kg",
        "sold": "118",
        "isLiked": false,
      },
      {
        "image": "images/explore_details/livingroom1_2.png",
        "name": "Living Room Sofa",
        "stock": "35",
        "rating": "4.7",
        "price1": 217,
        "size": "180cm,60cm,50cm",
        "type": "furniture",
        "weight": "37kg",
        "sold": "334",
        "isLiked": false,
      },
      {
        "image": "images/explore_details/livingroom1_3.png",
        "name": "Drawer",
        "stock": "110",
        "rating": "4.9",
        "price1": 86,
        "size": "120cm,50cm,40cm",
        "type": "Drawer",
        "weight": "14kg",
        "sold": "1.1K",
        "isLiked": false,
      },
    ]
  },
  {
    "room": "images/explore/livingroom2.png",
    "isLiked": false,
    "details": [
      {
        "image": "images/explore_details/livingroom2_1.png",
        "name": "Smart TV",
        "stock": "90",
        "rating": "4.3",
        "price1": 405,
        "size": "80cm,40cm,10cm",
        "type": "Gadgets",
        "weight": "6kg",
        "sold": "118",
        "isLiked": false,
      },
      {
        "image": "images/explore_details/livingroom2_2.png",
        "name": "Drawer",
        "stock": "35",
        "rating": "4.7",
        "price1": 140,
        "size": "180cm,60cm,50cm",
        "type": "furniture",
        "weight": "20kg",
        "sold": "339",
        "isLiked": false,
      },
    ]
  },
  {
    "room": "images/explore/livingroom3.png",
    "isLiked": false,
    "details": [
      {
        "image": "images/explore_details/livingroom3_1.png",
        "name": "Sofa",
        "stock": "23",
        "rating": "4.8",
        "price1": 125,
        "size": "80cm,40cm,40cm",
        "type": "furniture",
        "weight": "20kg",
        "sold": "118",
        "isLiked": false,
      },
      {
        "image": "images/explore_details/livingroom3_2.png",
        "name": "Circle Table",
        "stock": "35",
        "rating": "4.7",
        "price1": 80,
        "size": "80cm,60cm,50cm",
        "type": "furniture",
        "weight": "37kg",
        "sold": "334",
        "isLiked": false,
      },
      {
        "image": "images/explore_details/livingroom3_3.png",
        "name": "Chair",
        "stock": "110",
        "rating": "4.9",
        "price1": 86,
        "size": "70cm,50cm,40cm",
        "type": "furniture",
        "weight": "14kg",
        "sold": "1.1K",
        "isLiked": false,
      },
    ]
  },
  {
    "room": "images/explore/livingroom4.png",
    "isLiked": false,
    "details": [
      {
        "image": "images/explore_details/livingroom4_1.png",
        "name": "Wall CLock",
        "stock": "23",
        "rating": "4.8",
        "price1": 125,
        "size": "80cm,40cm,40cm",
        "type": "furniture",
        "weight": "4kg",
        "sold": "118",
        "isLiked": false,
      },
      {
        "image": "images/explore_details/livingroom4_2.png",
        "name": "Artificial Tree",
        "stock": "35",
        "rating": "4.7",
        "price1": 217,
        "size": "180cm,60cm,50cm",
        "type": "plants",
        "weight": "37kg",
        "sold": "334",
        "isLiked": false,
      },
      {
        "image": "images/explore_details/livingroom4_3.png",
        "name": "Table Lamp",
        "stock": "110",
        "rating": "4.9",
        "price1": 86,
        "size": "120cm,50cm,40cm",
        "type": "furniture",
        "weight": "14kg",
        "sold": "1.1K",
        "isLiked": false,
      },
    ]
  },
  {
    "room": "images/explore/office1.png",
    "isLiked": false,
    "details": [
      {
        "image": "images/explore_details/office1_1.png",
        "name": "Monitor",
        "stock": "23",
        "rating": "4.8",
        "price1": 125,
        "size": "80cm,40cm,40cm",
        "type": "electronics",
        "weight": "4kg",
        "sold": "118",
        "isLiked": false,
      },
      {
        "image": "images/explore_details/office1_2.png",
        "name": "Chair",
        "stock": "35",
        "rating": "4.7",
        "price1": 217,
        "size": "80cm,60cm,50cm",
        "type": "furniture",
        "weight": "3kg",
        "sold": "334",
        "isLiked": false,
      },
      {
        "image": "images/explore_details/office1_3.png",
        "name": "Wall Plant",
        "stock": "110",
        "rating": "4.9",
        "price1": 86,
        "size": "120cm,50cm,40cm",
        "type": "plants",
        "weight": "1kg",
        "sold": "1.1K",
        "isLiked": false,
      },
    ]
  },
  {
    "room": "images/explore/office2.png",
    "isLiked": false,
    "details": [
      {
        "image": "images/explore_details/office2_1.png",
        "name": "Monitor",
        "stock": "23",
        "rating": "4.8",
        "price1": "125",
        "size": "80cm,40cm,40cm",
        "type": "electronics",
        "weight": "4kg",
        "sold": "118",
        "isLiked": false,
      },
      {
        "image": "images/explore_details/office2_2.png",
        "name": "Chair",
        "stock": "35",
        "rating": "4.7",
        "price1": "217",
        "size": "80cm,60cm,50cm",
        "type": "furniture",
        "weight": "3kg",
        "sold": "334",
        "isLiked": false,
      },
      {
        "image": "images/explore_details/office2_3.png",
        "name": "Wall Plant",
        "stock": "110",
        "rating": "4.9",
        "price1": "86",
        "size": "120cm,50cm,40cm",
        "type": "plants",
        "weight": "1kg",
        "sold": "1.1K",
        "isLiked": false,
      },
    ]
  },
];
