List<Map<String, dynamic>> products = [
  {
    "image": "images/product/product1.png",
    "name": "Lemari Skandinavia",
    "price1": 148,
    "price2": 50,
    "sold": "68",
    "rating": "4.7",
    "stock": "100",
    "size": "210cm,110cm,80cm",
    "type": "scandinavia",
    "weight": "60kg",
    "isLiked": false,
  },
  {
    "image": "images/product/product2.png",
    "name": "Meja Skandinavia",
    "price1": 182,
    "price2": 50,
    "sold": "21",
    "rating": "4.7",
    "stock": "100",
    "size": "130cm,80cm,80cm",
    "type": "table",
    "weight": "46kg",
    "isLiked": false,
  },
  {
    "image": "images/product/product3.png",
    "name": "Fejka",
    "price1": 11,
    "price2": 50,
    "sold": "110",
    "rating": "4.2",
    "stock": "100",
    "size": "80cm,50cm,40cm",
    "type": "scandinavion",
    "weight": "10kg",
    "isLiked": false,
  },
  {
    "image": "images/product/product4.png",
    "name": "Lemari Skandinavia",
    "price1":22,
    "price2": 50,
    "sold": "38",
    "rating": "4.6",
    "stock": "100",
    "size": "85cm,60cm,60cm",
    "type": "scandinavion",
    "weight": "10kg",
    "isLiked": false,
  },
];
